draw_menu() {
    echo -e "  ${Y}${B}DISCOVERY${N}"
    echo "     1) Scan (Quick/Deep)     2) Show Devices"
    echo "     3) Nickname              4) Quick Select"
    echo "     5) Set Target            6) Multi-Target"
    echo "     7) Protect Me            8) Device Type"
    echo "     9) Attack All"
    echo ""
    echo -e "  ${Y}${B}ATTACK${N}"
    echo "    10) Smart Lag            11) Full Kill"
    echo "    12) Timed Kill           13) Restore / Stop Session"
    echo "    14) Re-apply             15) Online Check"
    echo "    16) Session Status"
    echo ""
    echo -e "  ${Y}${B}MONITOR${N}"
    echo "    17) Live Traffic         18) Rules / Latency"
    echo ""
    echo -e "  ${Y}${B}ANONYMITY${N}"
    echo "    19) Ghost Mode           20) Anon Menu"
    echo ""
    echo -e "  ${Y}${B}SYSTEM${N}"
    echo "    21) Custom Files         22) Persistence"
    echo "    23) Save / Log           99) Install Deps"
    echo "     0) Exit"
    echo ""
}
